// TheAlphaProject
// Discord: https://discord.gg/RzBMAKU
// Github:  https://github.com/The-Alpha-Project

using System;

namespace AlphaCoreExtractor.Helpers.Enums
{
    [Flags]
    public enum IntersectionType
    {
        NoIntersection = 0,
        Intersects = 1,
        Contained = 2,
        Touches = Intersects | Contained
    }

	public enum RecastExtractorErrors
    {
		Success = 0,
		MissingArgs = 2,
		LoadingGeomFailed = 3,
		LoadingGeomFailed2 = 4,
		BuildFailed = 5,		
    }

    public enum ContainmentType
    {
        Disjoint,
        Contains,
        Intersects
    }

    [Flags]
    public enum MOBN_Flags : short
    {
        NoChild = -1,
        XAxis = 0x0,
        YAxis = 0x1,
        ZAxis = 0x2,
        Flag_AxisMask = XAxis | YAxis | ZAxis,
        Leaf = 0x4,
    }

    [Flags]
    public enum MOPY_Flags : byte
    {
        None = 0,
        Unknown_0x1 = 0x01,
        NoCameraCollide = 0x02,
        Detail = 0x04,
        HasCollision = 0x08,
        Hint = 0x10,
        Render = 0x20,
        Unknown_0x40 = 0x40,
        CollideHit = 0x80,

        CollisionMask = Hint | CollideHit,
    }

    [Flags]
    public enum SMChunkFlags : uint
    {
        NONE = 0x0,
        FLAG_SHADOW = 0x1,
        FLAG_IMPASS = 0x2,
        FLAG_LQ_RIVER = 0x4,
        FLAG_LQ_OCEAN = 0x8,
        FLAG_LQ_MAGMA = 0x10,
        FLAG_LQ_DEEP = 0x14,
        HasLiquid = FLAG_LQ_RIVER | FLAG_LQ_OCEAN | FLAG_LQ_MAGMA
    }

    public enum GenerateObjs
    {
        Disabled,
        Enabled,
    }

    public enum GenerateMaps
    {
        Disabled,
        Enabled
    }

	public enum GenerateNavs
	{
		Disabled,
		Enabled,
	}


	public enum ParseSelection
    {
        Terrain,
        TerrainWMO,
        TerrainWMOMDX,
    }

    public enum CoordinatesType
    {
        Recast,
        WoW,
    }

	public enum LIGHT_TYPE
	{
		LIGHTTYPE_OMNI = 0x0,
		LIGHTTYPE_DIRECT = 0x1,
		LIGHTTYPE_AMBIENT = 0x2,
		NUM_MDL_LIGHT_TYPES = 0x3,
	}

	public enum GEOM_SHAPE
	{
		SHAPE_BOX = 0x0,
		SHAPE_CYLINDER = 0x1,
		SHAPE_SPHERE = 0x2,
		SHAPE_PLANE = 0x3,
		NUM_SHAPES = 0x4,
	}

	public enum MDLTEXOP
	{
		TEXOP_LOAD = 0x0,
		TEXOP_TRANSPARENT = 0x1,
		TEXOP_BLEND = 0x2,
		TEXOP_ADD = 0x3,
		TEXOP_ADD_ALPHA = 0x4,
		TEXOP_MODULATE = 0x5,
		TEXOP_MODULATE2X = 0x6,
		NUMTEXOPS = 0x7,
	}

	[Flags]
	public enum MDLGEO
	{
		MODEL_GEO_UNSHADED = 0x1,
		MODEL_GEO_SPHERE_ENV_MAP = 0x2,  // unused
		MODEL_GEO_WRAPWIDTH = 0x4,       // unused
		MODEL_GEO_WRAPHEIGHT = 0x8,      // unused
		MODEL_GEO_TWOSIDED = 0x10,
		MODEL_GEO_UNFOGGED = 0x20,
		MODEL_GEO_NO_DEPTH_TEST = 0x40,
		MODEL_GEO_NO_DEPTH_SET = 0x80,
		MODEL_GEO_UNKNOWN_1500 = 0x100, // ShaderSkin? waterfalls only
	}

	public enum PARTICLE_BLEND_MODE
	{
		PBM_BLEND = 0x0,
		PBM_ADD = 0x1,
		PBM_MODULATE = 0x2,
		PBM_MODULATE_2X = 0x3,
		PBM_ALPHA_KEY = 0x4,
		NUM_PARTICLE_BLEND_MODES = 0x5,
	}

	public enum PARTICLE_TYPE
	{
		PT_HEAD = 0x0,
		PT_TAIL = 0x1,
		PT_BOTH = 0x2,
		NUM_PARTICLE_TYPES = 0x3,
	}

	public enum PARTICLE_EMITTER_TYPE
	{
		PET_BASE = 0x0,
		PET_PLANE = 0x1,
		PET_SPHERE = 0x2,
		PET_SPLINE = 0x3,
		NUM_PARTICLE_EMITTER_TYPES = 0x4,
	}

	public enum MDLTRACKTYPE
	{
		TRACK_NO_INTERP = 0x0,
		TRACK_LINEAR = 0x1,
		TRACK_HERMITE = 0x2,
		TRACK_BEZIER = 0x3,
		NUM_TRACK_TYPES = 0x4,
	}

	[Flags]
	public enum TEXFLAGS : uint
	{
		WRAPWIDTH = 1,
		WRAPHEIGHT = 2
	}

	[Flags]
	public enum GENOBJECTFLAGS : uint
	{
		DONT_INHERIT_TRANSLATION = 0x00000001,
		DONT_INHERIT_SCALING = 0x00000002,
		DONT_INHERIT_ROTATION = 0x00000004,
		BILLBOARD = 0x00000008,
		BILLBOARD_LOCK_X = 0x00000010,
		BILLBOARD_LOCK_Y = 0x00000020,
		BILLBOARD_LOCK_Z = 0x00000040,
		GENOBJECT_MDLBONESECTION = 0x00000080,
		GENOBJECT_MDLLIGHTSECTION = 0x00000100,
		GENOBJECT_MDLEVENTSECTION = 0x00000200,
		GENOBJECT_MDLATTACHMENTSECTION = 0x00000400,
		GENOBJECT_MDLPARTICLEEMITTER2 = 0x00000800,
		GENOBJECT_MDLHITTESTSHAPE = 0x00001000,
		GENOBJECT_MDLRIBBONEMITTER = 0x00002000,
		PROJECT = 0x00004000,
		EMITTER_USES_TGA = 0x00008000,
		UNSHADED = 0x00008000,
		EMITTER_USES_MDL = 0x00010000,
		SORT_PRIMITIVES_FAR_Z = 0x00010000,
		LINE_EMITTER = 0x00020000,
		PARTICLE_UNFOGGED = 0x00040000,
		PARTICLE_USE_MODEL_SPACE = 0x00080000,
		PARTICLE_INHERIT_SCALE = 0x00100000,
		PARTICLE_INSTANT_VELOCITY_LIN = 0x00200000,
		PARTICLE_0XKILL = 0x00400000,
		PARTICLE_Z_VELOCITY_ONLY = 0x00800000,
		PARTICLE_TUMBLER = 0x01000000,
		PARTICLE_TAIL_GROWS = 0x02000000,
		PARTICLE_EXTRUDE = 0x04000000,
		PARTICLE_XYQUADS = 0x08000000,
		PARTICLE_PROJECT = 0x10000000,
		PARTICLE_FOLLOW = 0x20000000,
	}

	public enum ANIMENUMERATION : uint
	{
		ANIM_STAND = 0x0,
		ANIM_DEATH = 0x1,
		ANIM_SPELL = 0x2,
		ANIM_STOP = 0x3,
		ANIM_WALK = 0x4,
		ANIM_RUN = 0x5,
		ANIM_DEAD = 0x6,
		ANIM_RISE = 0x7,
		ANIM_STANDWOUND = 0x8,
		ANIM_COMBATWOUND = 0x9,
		ANIM_COMBATCRITICAL = 0xA,
		ANIM_SHUFFLE_LEFT = 0xB,
		ANIM_SHUFFLE_RIGHT = 0xC,
		ANIM_WALK_BACKWARDS = 0xD,
		ANIM_STUN = 0xE,
		ANIM_HANDS_CLOSED = 0xF,
		ANIM_ATTACKUNARMED = 0x10,
		ANIM_ATTACK1H = 0x11,
		ANIM_ATTACK2HTIGHT = 0x12,
		ANIM_ATTACK2HLOOSE = 0x13,
		ANIM_PARRYUNARMED = 0x14,
		ANIM_PARRY1H = 0x15,
		ANIM_PARRY2HTIGHT = 0x16,
		ANIM_PARRY2HLOOSE = 0x17,
		ANIM_PARRYSHIELD = 0x18,
		ANIM_READYUNARMED = 0x19,
		ANIM_READY1H = 0x1A,
		ANIM_READY2HTIGHT = 0x1B,
		ANIM_READY2HLOOSE = 0x1C,
		ANIM_READYBOW = 0x1D,
		ANIM_DODGE = 0x1E,
		ANIM_SPELLPRECAST = 0x1F,
		ANIM_SPELLCAST = 0x20,
		ANIM_SPELLCASTAREA = 0x21,
		ANIM_NPCWELCOME = 0x22,
		ANIM_NPCGOODBYE = 0x23,
		ANIM_BLOCK = 0x24,
		ANIM_JUMPSTART = 0x25,
		ANIM_JUMP = 0x26,
		ANIM_JUMPEND = 0x27,
		ANIM_FALL = 0x28,
		ANIM_SWIMIDLE = 0x29,
		ANIM_SWIM = 0x2A,
		ANIM_SWIM_LEFT = 0x2B,
		ANIM_SWIM_RIGHT = 0x2C,
		ANIM_SWIM_BACKWARDS = 0x2D,
		ANIM_ATTACKBOW = 0x2E,
		ANIM_FIREBOW = 0x2F,
		ANIM_READYRIFLE = 0x30,
		ANIM_ATTACKRIFLE = 0x31,
		ANIM_LOOT = 0x32,
		ANIM_SPELL_PRECAST_DIRECTED = 0x33,
		ANIM_SPELL_PRECAST_OMNI = 0x34,
		ANIM_SPELL_CAST_DIRECTED = 0x35,
		ANIM_SPELL_CAST_OMNI = 0x36,
		ANIM_SPELL_BATTLEROAR = 0x37,
		ANIM_SPELL_READYABILITY = 0x38,
		ANIM_SPELL_SPECIAL1H = 0x39,
		ANIM_SPELL_SPECIAL2H = 0x3A,
		ANIM_SPELL_SHIELDBASH = 0x3B,
		ANIM_EMOTE_TALK = 0x3C,
		ANIM_EMOTE_EAT = 0x3D,
		ANIM_EMOTE_WORK = 0x3E,
		ANIM_EMOTE_USE_STANDING = 0x3F,
		ANIM_EMOTE_EXCLAMATION = 0x40,
		ANIM_EMOTE_QUESTION = 0x41,
		ANIM_EMOTE_BOW = 0x42,
		ANIM_EMOTE_WAVE = 0x43,
		ANIM_EMOTE_CHEER = 0x44,
		ANIM_EMOTE_DANCE = 0x45,
		ANIM_EMOTE_LAUGH = 0x46,
		ANIM_EMOTE_SLEEP = 0x47,
		ANIM_EMOTE_SIT_GROUND = 0x48,
		ANIM_EMOTE_RUDE = 0x49,
		ANIM_EMOTE_ROAR = 0x4A,
		ANIM_EMOTE_KNEEL = 0x4B,
		ANIM_EMOTE_KISS = 0x4C,
		ANIM_EMOTE_CRY = 0x4D,
		ANIM_EMOTE_CHICKEN = 0x4E,
		ANIM_EMOTE_BEG = 0x4F,
		ANIM_EMOTE_APPLAUD = 0x50,
		ANIM_EMOTE_SHOUT = 0x51,
		ANIM_EMOTE_FLEX = 0x52,
		ANIM_EMOTE_SHY = 0x53,
		ANIM_EMOTE_POINT = 0x54,
		ANIM_ATTACK1HPIERCE = 0x55,
		ANIM_ATTACK2HLOOSEPIERCE = 0x56,
		ANIM_ATTACKOFF = 0x57,
		ANIM_ATTACKOFFPIERCE = 0x58,
		ANIM_SHEATHE = 0x59,
		ANIM_HIPSHEATHE = 0x5A,
		ANIM_MOUNT = 0x5B,
		ANIM_RUN_LEANRIGHT = 0x5C,
		ANIM_RUN_LEANLEFT = 0x5D,
		ANIM_MOUNT_SPECIAL = 0x5E,
		ANIM_KICK = 0x5F,
		ANIM_SITDOWN = 0x60,
		ANIM_SITTING = 0x61,
		ANIM_SITUP = 0x62,
		ANIM_SLEEPDOWN = 0x63,
		ANIM_SLEEPING = 0x64,
		ANIM_SLEEPUP = 0x65,
		ANIM_SITCHAIRLOW = 0x66,
		ANIM_SITCHAIRMEDIUM = 0x67,
		ANIM_SITCHAIRHIGH = 0x68,
		ANIM_LOADBOW = 0x69,
		ANIM_LOADRIFLE = 0x6A,
		ANIM_ATTACKTHROWN = 0x6B,
		ANIM_READYTHROWN = 0x6C,
		ANIM_HOLDBOW = 0x6D,
		ANIM_HOLDRIFLE = 0x6E,
		ANIM_HOLDTHROWN = 0x6F,
		ANIM_LOADTHROWN = 0x70,
		ANIM_EMOTE_SALUTE = 0x71,
		ANIM_KNEELDOWN = 0x72,
		ANIM_KNEELING = 0x73,
		ANIM_KNEELUP = 0x74,
		ANIM_ATTACKUNARMEDOFF = 0x75,
		ANIM_SPECIALUNARMED = 0x76,
		ANIM_STEALTHWALK = 0x77,
		ANIM_STEALTHSTAND = 0x78,
		ANIM_KNOCKDOWN = 0x79,
		ANIM_EATING = 0x7A,
		ANIM_USESTANDINGLOOP = 0x7B,
		ANIM_CHANNELCASTDIRECTED = 0x7C,
		ANIM_CHANNELCASTOMNI = 0x7D,
		ANIM_WHIRLWIND = 0x7E,
		ANIM_BIRTH = 0x7F,
		ANIM_USESTANDINGSTART = 0x80,
		ANIM_USESTANDINGEND = 0x81,
		ANIM_HOWL = 0x82,
		ANIM_DROWN = 0x83,
		ANIM_DROWNED = 0x84,
		ANIM_FISHINGCAST = 0x85,
		ANIM_FISHINGLOOP = 0x86,
		NUM_OBJECTANIMATIONS = 0x87,
		RESET_ANIMATION_INDICES0 = 0xFFFFFFFF,
		ANIM_GAMEOBJ_STAND = 0x0,
		ANIM_GAMEOBJ_CLOSED = 0x1,
		ANIM_GAMEOBJ_OPEN = 0x2,
		ANIM_GAMEOBJ_OPENED = 0x3,
		ANIM_GAMEOBJ_CLOSE = 0x4,
		ANIM_GAMEOBJ_DESTROY = 0x5,
		ANIM_GAMEOBJ_DESTROYED = 0x6,
		ANIM_GAMEOBJ_REBUILD = 0x7,
		ANIM_GAMEOBJ_CUSTOM0 = 0x8,
		ANIM_GAMEOBJ_CUSTOM1 = 0x9,
		ANIM_GAMEOBJ_CUSTOM2 = 0xA,
		ANIM_GAMEOBJ_CUSTOM3 = 0xB,
		NUM_GAMEOBJECTANIMATIONS = 0xC,
		FIRST_GAMEOBJECTANIMATION = 0x87,
		RESET_ANIMATION_INDICES1 = 0xFFFFFFFF,
		ANIM_EFFECT_STAND = 0x0,
		ANIM_EFFECT_HOLD = 0x1,
		ANIM_EFFECT_DECAY = 0x2,
		NUM_EFFECTANIMATIONS = 0x3,
		FIRST_EFFECTANIMATION = 0x93,
		RESET_ANIMATION_INDICES2 = 0xFFFFFFFF,
		ANIM_ITEM_STAND = 0x0,
		ANIM_ITEM_INFLIGHT = 0x1,
		ANIM_ITEM_BOWPULL = 0x2,
		ANIM_ITEM_BOWRELEASE = 0x3,
		NUM_ITEMANIMATIONS = 0x4,
		FIRST_ITEMANIMATION = 0x96,
		RESET_ANIMATION_INDICES3 = 0xFFFFFFFF,
		INVALID_ANIMATION = 0xFFFFFFFF,
	}
}
